# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Ubpa::ULua_CLI Ubpa::ULua_common Ubpa::ULua_compiler Ubpa::ULua_core)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target Ubpa::ULua_CLI
add_executable(Ubpa::ULua_CLI IMPORTED)

# Create imported target Ubpa::ULua_common
add_library(Ubpa::ULua_common INTERFACE IMPORTED)

set_target_properties(Ubpa::ULua_common PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/ULua_0_1_2/src/common"
  INTERFACE_SOURCES "${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lapi.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lcode.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lctype.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/ldebug.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/ldo.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/ldump.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lfunc.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lgc.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/llex.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lmem.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lobject.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lopcodes.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lparser.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lstate.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lstring.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/ltable.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/ltm.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lundump.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lvm.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lzio.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lauxlib.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lbaselib.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lbitlib.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lcorolib.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/ldblib.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/liolib.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lmathlib.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/loslib.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lstrlib.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/ltablib.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/linit.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/lutf8lib.c;${_IMPORT_PREFIX}/ULua_0_1_2/src/common/loadlib_rel.c;${_IMPORT_PREFIX}/ULua_0_1_2/include/lauxlib.h;${_IMPORT_PREFIX}/ULua_0_1_2/include/lua.h;${_IMPORT_PREFIX}/ULua_0_1_2/include/lua.hpp;${_IMPORT_PREFIX}/ULua_0_1_2/include/luaconf.h;${_IMPORT_PREFIX}/ULua_0_1_2/include/lualib.h"
)

# Create imported target Ubpa::ULua_compiler
add_executable(Ubpa::ULua_compiler IMPORTED)

set_target_properties(Ubpa::ULua_compiler PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/ULua_0_1_2/include"
)

# Create imported target Ubpa::ULua_core
add_library(Ubpa::ULua_core SHARED IMPORTED)

set_target_properties(Ubpa::ULua_core PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/ULua_0_1_2/include"
)

if(CMAKE_VERSION VERSION_LESS 3.1.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.1.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/ULuaTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
